/* Generated by tools/generate_game_over.py. */
#define GAME_OVER_SCORE_PEN 63
#define GAME_OVER_SCORE_CENTER_X 123
#define GAME_OVER_SCORE_Y 87
static const unsigned char gameOverDigits[10][7]={
{14,17,19,21,25,17,14},
{4,12,4,4,4,4,14},
{14,17,1,2,4,8,31},
{30,1,1,14,1,1,30},
{2,6,10,18,31,2,2},
{31,16,30,1,1,17,14},
{6,8,16,30,17,17,14},
{31,1,2,4,8,8,8},
{14,17,17,14,17,17,14},
{14,17,17,15,1,2,28}
};
