#ifndef SPARKPAW_PERFORMANCE_PROFILE_H
#define SPARKPAW_PERFORMANCE_PROFILE_H

#include <dos/dos.h>
#include <exec/types.h>

enum PerformanceProfileSlot {
    PERF_GAME_UPDATE,
    PERF_COPPER_PATCH,
    PERF_BOB_PASS,
    PERF_PUBLISH_WAIT,
    PERF_PLAYER,
    PERF_ENEMIES,
    PERF_COLLECTIBLES,
    PERF_PROJECTILES,
    PERF_INPUT,
    PERF_PLAYER_ANIMATE,
    PERF_ENEMY_CONTACT,
    PERF_PROJECTILE_CONTACT,
    PERF_AUDIO_UPDATE,
    PERF_COPPER_COPY,
    PERF_SPRITE_STAGE,
    PERF_HUD_UPDATE,
    PERF_SCROLL_PATCH,
    PERF_RING_ROLL,
    PERF_RING_DYNAMIC,
    PERF_BOB_PROJECTILE_RESTORE,
    PERF_BOB_ENEMY_RESTORE,
    PERF_BOB_COLLECTIBLE_RESTORE,
    PERF_BOB_SPLASH_RESTORE,
    PERF_BOB_WATER,
    PERF_BOB_COMPACT_TARGET,
    PERF_BOB_SPLASH_DRAW,
    PERF_BOB_COLLECTIBLE_DRAW,
    PERF_BOB_ENEMY_DRAW,
    PERF_BOB_PROJECTILE_DRAW,
    PERF_BOB_FINAL_WAIT,
    PERF_ENEMY_PARKED,
    PERF_ENEMY_ACTIVE,
    PERF_ENEMY_RESPAWN,
    PERF_ENEMY_ACTIVATE,
    PERF_SLOT_COUNT
};

#ifdef SPARKPAW_RENDER_DIAGNOSTIC
ULONG performanceProfileBegin(void);
void performanceProfileEnd(enum PerformanceProfileSlot slot,ULONG start);
void performanceProfileWrite(BPTR file);
#else
#define performanceProfileBegin() 0UL
#define performanceProfileEnd(slot,start) do { } while(0)
#endif

#endif
