/* Compile the accepted Stormrail compositor as its own renderer unit. */
#define rendererLoadGameplay rendererStormrailLoadGameplay
#define rendererPrepareGameplay rendererStormrailPrepareGameplay
#define rendererResetGameplay rendererStormrailResetGameplay
#define rendererCleanup rendererStormrailCleanup
#define rendererCopperList rendererStormrailCopperList
#define rendererUpdateGameplay rendererStormrailUpdateGameplay
#define rendererPublishGameplay rendererStormrailPublishGameplay
#define rendererDrawGameplayBobs rendererStormrailDrawGameplayBobs
#define rendererWriteExtraLifeProof rendererStormrailWriteExtraLifeProof
#define rendererReplayPresentationValid rendererStormrailReplayPresentationValid
#define rendererCaptureStormrailProof rendererStormrailCaptureStormrailProof
#define rendererWriteStormrailProofFrames rendererStormrailWriteStormrailProofFrames
#define rendererStormrailUnsafeBlits rendererStormrailUnsafeBlitsInternal
#define rendererDiagnosticUpdateEntry rendererStormrailDiagnosticUpdateEntry
#define rendererDiagnosticPublicationEntry rendererStormrailDiagnosticPublicationEntry
#define rendererDiagnosticPublicationExit rendererStormrailDiagnosticPublicationExit
#define rendererDiagnosticBobEntry rendererStormrailDiagnosticBobEntry
#define rendererDiagnosticBobExit rendererStormrailDiagnosticBobExit
#define rendererDiagnosticBoundary rendererStormrailDiagnosticBoundary
#define rendererWriteDiagnosticLog rendererStormrailWriteDiagnosticLog
#define rendererPhase6PeakChipFree rendererStormrailPhase6PeakChipFree
#define rendererPhase6PeakChipLargest rendererStormrailPhase6PeakChipLargest
#define rendererPhase6PeakFastFree rendererStormrailPhase6PeakFastFree
#define rendererPhase6PeakFastLargest rendererStormrailPhase6PeakFastLargest
#include "renderer.c"
