/* Compile the Level-1 renderer independently so later section code cannot
   perturb its 68020 hot-path code generation. Public ownership is provided by
   renderer_dispatch.c. */
#define SPARKPAW_LEVEL1_RENDERER_TU_ISOLATION
#define rendererLoadGameplay rendererLevel1LoadGameplay
#define rendererPrepareGameplay rendererLevel1PrepareGameplay
#define rendererResetGameplay rendererLevel1ResetGameplay
#define rendererCleanup rendererLevel1Cleanup
#define rendererCopperList rendererLevel1CopperList
#define rendererUpdateGameplay rendererLevel1UpdateGameplay
#define rendererPublishGameplay rendererLevel1PublishGameplay
#define rendererDrawGameplayBobs rendererLevel1DrawGameplayBobs
#define rendererWriteExtraLifeProof rendererLevel1WriteExtraLifeProof
#define rendererReplayPresentationValid rendererLevel1ReplayPresentationValid
#define rendererCaptureStormrailProof rendererLevel1CaptureStormrailProof
#define rendererWriteStormrailProofFrames rendererLevel1WriteStormrailProofFrames
#define rendererStormrailUnsafeBlits rendererLevel1StormrailUnsafeBlits
#define rendererDiagnosticUpdateEntry rendererLevel1DiagnosticUpdateEntry
#define rendererDiagnosticPublicationEntry rendererLevel1DiagnosticPublicationEntry
#define rendererDiagnosticPublicationExit rendererLevel1DiagnosticPublicationExit
#define rendererDiagnosticBobEntry rendererLevel1DiagnosticBobEntry
#define rendererDiagnosticBobExit rendererLevel1DiagnosticBobExit
#define rendererDiagnosticBoundary rendererLevel1DiagnosticBoundary
#define rendererWriteDiagnosticLog rendererLevel1WriteDiagnosticLog
#define rendererPhase6PeakChipFree rendererLevel1Phase6PeakChipFree
#define rendererPhase6PeakChipLargest rendererLevel1Phase6PeakChipLargest
#define rendererPhase6PeakFastFree rendererLevel1Phase6PeakFastFree
#define rendererPhase6PeakFastLargest rendererLevel1Phase6PeakFastLargest
#include "renderer.c"
