#!/usr/bin/env python3
"""Build the isolated Stormrail rear and foreground proof assets."""

from pathlib import Path

from PIL import Image, ImageDraw

from generate_runtime_assets import (
    FRONT16, REAR8_BANDS, save_spbm,
)
from generate_intro_proof import GLYPHS, medium_text


ROOT = Path(__file__).resolve().parents[1]
CONCEPT = ROOT / "assets" / "concept"
RUNTIME = ROOT / "assets" / "runtime"
PALETTE_HEADER = ROOT / "src" / "stormrail_palette_table.h"
REAR_SOURCE = CONCEPT / "sparkpaw-stormrail-rear-panorama-v3.png"
FLIGHT_REAR_SOURCE = CONCEPT / "sparkpaw-stormrail-route-spans-concept-v2.png"
FRONT_SOURCE = CONCEPT / "sparkpaw-stormrail-foreground-kit-v1-chroma.png"
LOADING_SOURCE = CONCEPT / "sparkpaw-stormrail-loading-concept-v1.png"
LEVEL1_KIT = CONCEPT / "sparkpaw-foreground-kit-concept-v2.png"
WORLD_W, WORLD_H, REAR_W = 3392, 256, 1120
GAMEPLAY_H = 208

# Four authored route palettes share stable dark-to-light pen meanings. The
# flight Copper morphs between them as the bounded 768px span advances.
FLIGHT_ROUTE_BANKS = (
    (((0,0,1),(1,1,3),(3,2,6),(5,3,8),(3,5,6),(6,5,9),(10,7,12),(14,11,15)),
     ((0,0,1),(1,1,3),(2,3,5),(4,3,7),(2,5,5),(5,6,8),(9,8,11),(12,11,14)),
     ((0,0,1),(0,1,2),(1,2,3),(2,3,4),(2,4,3),(4,5,5),(7,6,8),(10,9,11))),
    (((0,0,1),(1,2,3),(2,4,5),(3,5,7),(4,6,6),(6,7,8),(8,9,10),(11,12,13)),
     ((0,0,1),(1,2,3),(2,4,5),(3,5,6),(4,6,6),(6,8,8),(9,10,11),(12,13,13)),
     ((0,0,1),(0,1,2),(1,3,3),(2,4,4),(3,5,4),(5,6,6),(7,8,8),(10,11,11))),
    (((0,0,1),(1,2,3),(3,3,5),(4,5,7),(5,6,7),(7,8,9),(10,11,12),(13,14,15)),
     ((0,0,1),(1,2,3),(2,4,5),(4,5,6),(5,7,7),(7,9,9),(10,12,12),(14,15,15)),
     ((0,0,1),(0,1,2),(1,3,3),(2,4,4),(3,5,4),(5,7,6),(8,9,8),(11,12,11))),
    (((0,0,1),(0,2,3),(1,3,5),(2,5,7),(2,6,7),(4,8,9),(7,11,12),(10,14,15)),
     ((0,0,1),(0,2,3),(1,4,5),(2,5,6),(3,7,7),(5,9,9),(8,12,12),(11,15,15)),
     ((0,0,1),(0,1,2),(0,3,3),(1,4,4),(2,5,4),(3,7,6),(6,9,8),(9,12,11))),
)
FLIGHT_ROUTE_ANCHORS = (0, 128, 338, 565, 700, 768)
FLIGHT_ROUTE_REGIONS = (3, 0, 1, 2, 3, 3)
FLIGHT_PALETTE_STAGES = 13


def runtime_route_palette(phase):
    """Return the exact 12-bit Copper palette formerly calculated in C."""
    segment = next(i for i in range(5)
                   if phase < FLIGHT_ROUTE_ANCHORS[i + 1])
    left, right = FLIGHT_ROUTE_ANCHORS[segment:segment + 2]
    left_region = FLIGHT_ROUTE_REGIONS[segment]
    right_region = FLIGHT_ROUTE_REGIONS[segment + 1]
    spatial = []
    for anchor in range(3):
        anchor_colors = []
        for pen in range(8):
            anchor_colors.append(tuple(
                (FLIGHT_ROUTE_BANKS[left_region][anchor][pen][component] *
                 (right - phase) +
                 FLIGHT_ROUTE_BANKS[right_region][anchor][pen][component] *
                 (phase - left)) // (right - left)
                for component in range(3)))
        spatial.append(anchor_colors)
    palette = []
    for stage in range(FLIGHT_PALETTE_STAGES):
        for pen in range(8):
            value = 0
            for component in range(3):
                if stage == 0:
                    result = spatial[0][pen][component]
                elif stage <= 4:
                    result = (spatial[0][pen][component] * (4 - stage) +
                              spatial[1][pen][component] * stage) // 4
                else:
                    step = stage - 4
                    result = (spatial[1][pen][component] * (8 - step) +
                              spatial[2][pen][component] * step) // 8
                value |= result << (8 - component * 4)
            palette.append(value)
    return tuple(palette)


def build_palette_header():
    palettes = []
    indices = []
    for phase in range(768):
        palette = runtime_route_palette(phase)
        if palette not in palettes:
            palettes.append(palette)
        indices.append(palettes.index(palette))
    assert len(palettes) == 23
    lines = [
        "#ifndef SPARKPAW_STORMRAIL_PALETTE_TABLE_H",
        "#define SPARKPAW_STORMRAIL_PALETTE_TABLE_H",
        "",
        "/* Generated by tools/generate_stormrail_environment.py. */",
        "#define STORMRAIL_ROUTE_PALETTE_COUNT 23",
        "static const UBYTE stormRoutePalettePhase[768]={",
    ]
    for offset in range(0, len(indices), 32):
        lines.append("    " + ",".join(map(str, indices[offset:offset + 32])) + ",")
    palette_words = FLIGHT_PALETTE_STAGES * 8
    assert all(len(palette) == palette_words for palette in palettes)
    lines += ["};", "", f"static const UWORD stormRoutePaletteValues[23][{palette_words}]={{"]
    for palette in palettes:
        lines.append("    {")
        for offset in range(0, palette_words, 13):
            lines.append("        " + ",".join(f"0x{v:03x}" for v in
                                                  palette[offset:offset + 13]) + ",")
        lines.append("    },")
    lines += ["};", "", "#endif", ""]
    PALETTE_HEADER.write_text("\n".join(lines))


def storm_rear_palette_for_y(y):
    schedule = [(60 + step * 12, 0, 1, step, 4) for step in range(1, 5)]
    schedule += [(108 + step * 11, 1, 2, step, 8) for step in range(1, 9)]
    source, target, step, steps = 0, 0, 0, 1
    for at, source_i, target_i, step_i, steps_i in schedule:
        if y < at:
            break
        source, target, step, steps = source_i, target_i, step_i, steps_i
    return [tuple(((REAR8_BANDS[source][pen][channel] * (steps - step) +
                    REAR8_BANDS[target][pen][channel] * step) // steps) * 17
                  for channel in range(3)) for pen in range(8)]


def nearest(rgb, palette):
    return min(range(len(palette)), key=lambda i: sum((rgb[c] - palette[i][c]) ** 2 for c in range(3)))


def mix_palette(left, right, step, steps):
    return [tuple(((left[pen][channel] * (steps - step) +
                    right[pen][channel] * step) // steps) * 17
                  for channel in range(3)) for pen in range(8)]


def flight_anchor_palette(x, vertical_anchor):
    x %= 768
    for segment in range(len(FLIGHT_ROUTE_ANCHORS) - 1):
        left = FLIGHT_ROUTE_ANCHORS[segment]
        right = FLIGHT_ROUTE_ANCHORS[segment + 1]
        if x < right:
            region = FLIGHT_ROUTE_REGIONS[segment]
            next_region = FLIGHT_ROUTE_REGIONS[segment + 1]
            return mix_palette(FLIGHT_ROUTE_BANKS[region][vertical_anchor],
                               FLIGHT_ROUTE_BANKS[next_region][vertical_anchor],
                               x - left, right - left)
    raise AssertionError("unreachable route phase")


def flight_palette_for_xy(x, y):
    top = flight_anchor_palette(x, 0)
    middle = flight_anchor_palette(x, 1)
    bottom = flight_anchor_palette(x, 2)
    if y < 108:
        step = max(0, min(4, (y - 60) // 12))
        return mix_palette(tuple(tuple(c // 17 for c in rgb) for rgb in top),
                           tuple(tuple(c // 17 for c in rgb) for rgb in middle),
                           step, 4)
    step = max(0, min(8, (y - 108) // 11))
    return mix_palette(tuple(tuple(c // 17 for c in rgb) for rgb in middle),
                       tuple(tuple(c // 17 for c in rgb) for rgb in bottom),
                       step, 8)


def build_rear():
    source = Image.open(REAR_SOURCE).convert("RGB")
    scaled_h = round(source.height * REAR_W / source.width)
    source = source.resize((REAR_W, scaled_h), Image.Resampling.LANCZOS)
    top = max(0, min(scaled_h - GAMEPLAY_H, 24))
    source = source.crop((0, top, REAR_W, top + GAMEPLAY_H))

    indexed = Image.new("P", (REAR_W, WORLD_H), 0)
    preview = Image.new("RGB", (REAR_W, GAMEPLAY_H))
    src = source.load()
    dst = indexed.load()
    shown = preview.load()
    for y in range(GAMEPLAY_H):
        palette = storm_rear_palette_for_y(y)
        for x in range(REAR_W):
            pen = nearest(src[x, y], palette)
            dst[x, y] = pen
            shown[x, y] = palette[pen]
    # Runtime flight scrolls across a bounded 768px panorama. Append its first
    # fetch-width columns so a Copper viewport can cross the logical wrap with
    # no pointer wrap or whole-screen jump. Feather only the tail of the base
    # span toward its head; the accepted panorama remains the visual source.
    loop_w = 768
    overlap = REAR_W - loop_w
    feather = 96
    for y in range(GAMEPLAY_H):
        palette = storm_rear_palette_for_y(y)
        for i in range(feather):
            x = loop_w - feather + i
            a = (i + 1) / feather
            left = shown[x, y]
            right = shown[i, y]
            rgb = tuple(round(left[c] * (1 - a) + right[c] * a)
                        for c in range(3))
            pen = nearest(rgb, palette)
            dst[x, y] = pen
            shown[x, y] = palette[pen]
        for x in range(overlap):
            dst[loop_w + x, y] = dst[x, y]
            shown[loop_w + x, y] = shown[x, y]
    save_spbm(RUNTIME / "stormrail-rear.spbm", indexed,
              storm_rear_palette_for_y(0), depth=3)
    preview.resize((REAR_W * 2, GAMEPLAY_H * 2), Image.Resampling.NEAREST).save(
        CONCEPT / "sparkpaw-stormrail-rear-aga8-preview-v3.png"
    )


def build_flight_rear():
    source = Image.open(FLIGHT_REAR_SOURCE).convert("RGB").resize(
        (896, 256), Image.Resampling.LANCZOS)
    source = source.crop((0, 29, 896, 29 + GAMEPLAY_H))
    # Standard overlap-add loop: the 128px source tail is folded over the
    # beginning. Therefore output x=767 continues into the tail represented
    # at x=0, while x=127 has smoothly become the untouched route head.
    pixels = source.load()
    feather = 128
    for y in range(GAMEPLAY_H):
        for i in range(feather):
            amount = i / (feather - 1)
            amount = amount * amount * (3 - 2 * amount)
            head = pixels[i, y]
            tail = pixels[768 + i, y]
            pixels[i, y] = tuple(round(tail[c] * (1 - amount) +
                                        head[c] * amount) for c in range(3))

    indexed = Image.new("P", (REAR_W, WORLD_H), 0)
    preview = Image.new("RGB", (REAR_W, GAMEPLAY_H))
    src, dst, shown = source.load(), indexed.load(), preview.load()
    for y in range(GAMEPLAY_H):
        error = [0.0, 0.0, 0.0]
        # Encode the complete loop against one stable semantic pen ordering.
        # Runtime may recolour those roles globally, but a given 3-bit value
        # must never change meaning at a horizontal route boundary.
        encoding_palette = flight_palette_for_xy(338, y)
        for x in range(768):
            adjusted = tuple(max(0, min(255, round(src[x, y][c] + error[c])))
                             for c in range(3))
            pen = nearest(adjusted, encoding_palette)
            dst[x, y] = pen
            shown[x, y] = flight_palette_for_xy(x, y)[pen]
            for c in range(3):
                error[c] = (adjusted[c] - encoding_palette[pen][c]) * 0.55
        for x in range(REAR_W - 768):
            dst[768 + x, y] = dst[x, y]
            shown[768 + x, y] = shown[x, y]
    save_spbm(RUNTIME / "stormrail-flight-rear.spbm", indexed,
              flight_palette_for_xy(0, 0), depth=3)
    preview.resize((REAR_W * 2, GAMEPLAY_H * 2),
                   Image.Resampling.NEAREST).save(
        CONCEPT / "sparkpaw-stormrail-flight-rear-aga8-preview-v1.png")


def keyed_piece(sheet, box, scale):
    piece = sheet.crop(box).convert("RGB")
    piece = piece.resize((max(1, round(piece.width * scale)), max(1, round(piece.height * scale))),
                         Image.Resampling.LANCZOS)
    rgba = Image.new("RGBA", piece.size)
    src = piece.load()
    dst = rgba.load()
    for y in range(piece.height):
        for x in range(piece.width):
            r, g, b = src[x, y]
            # ImageGen chroma is not perfectly flat after antialiasing.
            if r > 180 and b > 150 and g < 90 and r > g * 2:
                dst[x, y] = (0, 0, 0, 0)
            else:
                dst[x, y] = (r, g, b, 255)
    return rgba


def paste(canvas, piece, x, y):
    canvas.alpha_composite(piece, (x, y))


def build_front():
    sheet = Image.open(FRONT_SOURCE).convert("RGB")
    top_rail = keyed_piece(sheet, (35, 42, 1125, 210), 0.42)
    thin_rail = keyed_piece(sheet, (35, 245, 1125, 390), 0.42)
    ring = keyed_piece(sheet, (35, 400, 535, 755), 0.42)
    upper_curve = keyed_piece(sheet, (1210, 35, 1525, 345), 0.42)
    lower_curve = keyed_piece(sheet, (1210, 385, 1525, 690), 0.42)
    conduit = keyed_piece(sheet, (535, 675, 1200, 800), 0.42)
    lower_rail = keyed_piece(sheet, (340, 800, 1200, 930), 0.42)
    floor_line = keyed_piece(sheet, (45, 938, 1510, 990), 0.42)

    world = Image.new("RGBA", (WORLD_W, WORLD_H), (0, 0, 0, 0))
    # Gate 1 is one short raised cliff made from Level 1's accepted floor lip
    # and the same FRONT16 material roles. It ends in real transparency at
    # x=176; no hidden path or corridor exists beyond the broken edge.
    draw = ImageDraw.Draw(world)
    steel = FRONT16[8] + (255,)
    dark = FRONT16[1] + (255,)
    violet = FRONT16[12] + (255,)
    cyan = FRONT16[6] + (255,)
    # Reuse the accepted Level-1 modular facade itself rather than drawing a
    # Stormrail approximation. The bottom kit row supplies the pale cap,
    # masonry bays, moss and cyan machinery at one uniform native reduction.
    level1_kit = Image.open(LEVEL1_KIT).convert("RGBA")
    facade = level1_kit.crop((84, 892, 1456, 970)).resize(
        (190, 40), Image.Resampling.LANCZOS)
    pixels = facade.load()
    for py in range(facade.height):
        broken_edge = 176 - max(0, (py - 5) // 5) * 3
        for px in range(facade.width):
            if px >= broken_edge:
                pixels[px, py] = (0, 0, 0, 0)
    world.alpha_composite(facade, (0, 168))
    # Strengthen only the exposed broken face after reduction; the rest stays
    # sourced from the accepted Level-1 kit.
    draw.line((175,168,172,182,166,195,158,207), fill=steel, width=2)
    draw.line((171,177,167,189,161,202), fill=cyan, width=2)

    indexed = Image.new("P", world.size, 0)
    indexed.putpalette(sum(FRONT16, ()) + (0,) * (768 - len(FRONT16) * 3))
    src = world.load()
    dst = indexed.load()
    for y in range(GAMEPLAY_H):
        for x in range(WORLD_W):
            r, g, b, a = src[x, y]
            if a >= 96:
                dst[x, y] = nearest((r, g, b), FRONT16[1:]) + 1
    save_spbm(RUNTIME / "stormrail-front.spbm", indexed, FRONT16, depth=4)

    review = indexed.crop((0, 0, 1120, GAMEPLAY_H)).convert("RGB")
    review.resize((2240, GAMEPLAY_H * 2), Image.Resampling.NEAREST).save(
        CONCEPT / "sparkpaw-stormrail-front-aga16-preview-v1.png"
    )


def build_loading():
    source = Image.open(LOADING_SOURCE).convert("RGB")
    crop_w = round(source.height * 5 / 4)
    left = max(0, (source.width - crop_w) // 2)
    source = source.crop((left, 0, left + crop_w, source.height))
    source = source.resize((320, 256), Image.Resampling.LANCZOS)
    draw = ImageDraw.Draw(source)
    # Keep generated art free of lettering; apply crisp deterministic glyphs.
    title = "STORMRAIL"
    title_x = (320 - len(title) * 9 + 1) // 2
    medium_text(draw, title, title_x + 1, 221, (4, 5, 15))
    medium_text(draw, title, title_x, 220, (108, 221, 255))
    loading = "LOADING"
    loading_x = (320 - len(loading) * 9 + 1) // 2
    medium_text(draw, loading, loading_x + 1, 239, (4, 5, 15))
    medium_text(draw, loading, loading_x, 238, (241, 226, 174))

    quantized = source.quantize(colors=63, method=Image.Quantize.MEDIANCUT,
                                dither=Image.Dither.NONE)
    raw_palette = quantized.getpalette()
    colours = [tuple(raw_palette[i:i + 3]) for i in range(0, 63 * 3, 3)]
    indexed = Image.new("P", (320, 256), 0)
    indexed.putdata([value + 1 for value in quantized.getdata()])
    palette = [(0, 0, 0)] + colours
    indexed.putpalette(sum(palette, ()) + (0,) * (768 - 64 * 3))
    save_spbm(RUNTIME / "stormrail-loading.spbm", indexed, palette, depth=6)
    indexed.save(CONCEPT / "sparkpaw-stormrail-loading-aga64-preview-v1.png")
    assert (RUNTIME / "stormrail-loading.spbm").read_bytes()[12:15] == b"\0\0\0"


if __name__ == "__main__":
    RUNTIME.mkdir(parents=True, exist_ok=True)
    build_rear()
    build_flight_rear()
    build_front()
    build_loading()
    build_palette_header()
    print("generated Stormrail environment assets")
