"""Approved V2 concept -> shared 64-colour AGA game-over plate and digits.
No edition-specific art reduction. Text is drawn once before display takeover.
"""
from pathlib import Path
from PIL import Image, ImageDraw
from generate_score_screen import GLYPHS, spbm
ROOT=Path(__file__).resolve().parents[1]
# User-marked open area: native x40..206, y0..156.
TEXT_CENTER_X=123
SCORE_Y=87
def text(im,label,cx,y,scale,colour):
 d=ImageDraw.Draw(im);x=cx-(len(label)*6-1)*scale//2
 for c in label:
  for yy,row in enumerate(GLYPHS.get(c,('00000',)*7)):
   for xx,v in enumerate(row):
    if v=='1':d.rectangle((x+xx*scale,y+yy*scale,x+(xx+1)*scale-1,y+(yy+1)*scale-1),fill=colour)
  x+=6*scale

def main():
 im=Image.open(ROOT/'assets/concept/sparkpaw-game-over-v2.png').convert('RGB').resize((320,256),Image.Resampling.LANCZOS)
 text(im,'GAME OVER',TEXT_CENTER_X,37,2,(0,0,0));text(im,'GAME OVER',TEXT_CENTER_X,35,2,(246,209,135))
 for dx,dy in ((-1,0),(1,0),(0,-1),(0,1)):
  text(im,'TOTAL CAMPAIGN SCORE',TEXT_CENTER_X+dx,70+dy,1,(8,12,30))
  text(im,'PRESS FIRE TO CONTINUE',TEXT_CENTER_X+dx,113+dy,1,(8,12,30))
 text(im,'TOTAL CAMPAIGN SCORE',TEXT_CENTER_X,70,1,(139,216,232))
 text(im,'PRESS FIRE TO CONTINUE',TEXT_CENTER_X,113,1,(246,209,135))
 indexed=im.quantize(colors=62,dither=Image.Dither.NONE)
 pal=[(0,0,0)]+[tuple(indexed.getpalette()[i:i+3]) for i in range(0,186,3)]+[(255,230,169)]
 indexed=indexed.point([min(i+1,63) for i in range(256)])
 indexed.putpalette([v for rgb in pal for v in rgb])
 (ROOT/'assets/runtime/game-over.spbm').write_bytes(spbm(indexed,320,256))
 preview=indexed.copy();text(preview,'000040',TEXT_CENTER_X,SCORE_Y,2,63)
 preview.save(ROOT/'assets/concept/sparkpaw-game-over-aga64-preview.png')
 preview.resize((960,768),Image.Resampling.NEAREST).save(ROOT/'build/game-over-work/game-over-preview-3x.png')
 digits=['{'+','.join(str(int(row,2)) for row in GLYPHS[str(n)])+'}' for n in range(10)]
 (ROOT/'src/game_over_art.h').write_text('/* Generated by tools/generate_game_over.py. */\n#define GAME_OVER_SCORE_PEN 63\n#define GAME_OVER_SCORE_CENTER_X '+str(TEXT_CENTER_X)+'\n#define GAME_OVER_SCORE_Y '+str(SCORE_Y)+'\nstatic const unsigned char gameOverDigits[10][7]={\n'+',\n'.join(digits)+'\n};\n')
 assert pal[0]==(0,0,0)
 print('Shared AGA plate:',len(spbm(indexed,320,256)),'bytes, 64 colours')
if __name__=='__main__':main()
