"""Small immutable READY background/font, using the accepted palette and art.

No runtime assets are overwritten. Generated RLE is expanded once into Fast RAM.
"""
from pathlib import Path
from collections import deque
from PIL import Image
from generate_ready_screen import ready_background, GLYPHS, planar_bytes

ROOT = Path(__file__).resolve().parents[1]

def generate():
    raw = (ROOT / 'assets/runtime/sparkpaw-ready-screen.spbm').read_bytes()
    palette = raw[12:204]
    pal = Image.new('P', (1, 1))
    pal.putpalette(list(palette) + [0] * (768-len(palette)))
    im = ready_background().quantize(palette=pal, dither=Image.Dither.NONE)
    # Preserve the added side strips bit-for-bit from accepted runtime art.
    for y in range(118,222):
        for x in list(range(48,64))+list(range(256,272)):
            im.putpixel((x,y),sum(((raw[204+p*10240+y*40+x//8]>>(7-x%8))&1)<<p for p in range(6)))
    patch = im.crop((48, 118, 272, 222))
    _, planes = planar_bytes(patch, 6)
    data = bytes(planes)
    packed = bytearray()
    pos = 0
    while pos < len(data):
        end = pos + 1
        while end < min(pos+255, len(data)) and data[end] == data[pos]:
            end += 1
        packed.extend((end-pos, data[pos]))
        pos = end
    rgb = im.convert('RGB')
    dark = [[all(v <= limit for v, limit in zip(rgb.getpixel((x,y)), (12,18,35)))
             for x in range(320)] for y in range(256)]
    safe = [[all(dark[yy][xx] for yy in range(max(0,y-1),min(256,y+2))
                 for xx in range(max(0,x-1),min(320,x+2)))
             for x in range(320)] for y in range(256)]
    seen=set(); q=deque()
    for y in range(256):
        for x in (0,319):
            if safe[y][x]: seen.add((x,y)); q.append((x,y))
    for x in range(320):
        for y in (0,255):
            if safe[y][x] and (x,y) not in seen: seen.add((x,y)); q.append((x,y))
    while q:
        x,y=q.popleft()
        for xx,yy in ((x-1,y),(x+1,y),(x,y-1),(x,y+1)):
            if 0<=xx<320 and 0<=yy<256 and safe[yy][xx] and (xx,yy) not in seen:
                seen.add((xx,yy)); q.append((xx,yy))
    mask=bytearray(2912)
    for x,y in seen:
        if 48<=x<272 and 118<=y<222: mask[(y-118)*28+(x-48)//8] |= 128>>(x%8)
    GLYPHS.update({
        'Q': ('01110','10001','10001','10001','10101','10010','01101'),
        'X': ('10001','10001','01010','00100','01010','10001','10001'),
        'Z': ('11111','00001','00010','00100','01000','10000','11111'),
        '+': ('00000','00100','00100','11111','00100','00100','00000'),
        '<': ('00001','00010','00100','01000','00100','00010','00001'),
        '>': ('10000','01000','00100','00010','00100','01000','10000'),
        '/': ('00001','00001','00010','00100','01000','10000','10000'),
        '3': ('11110','00001','00001','01110','00001','00001','11110'),
        '4': ('00010','00110','01010','10010','11111','00010','00010'),
        '5': ('11111','10000','10000','11110','00001','00001','11110'),
        '7': ('11111','00001','00010','00100','01000','01000','01000'),
        '8': ('01110','10001','10001','01110','10001','10001','01110'),
        '9': ('01110','10001','10001','01111','00001','00001','01110'),
    })
    assert all(chr(c) in GLYPHS for c in range(65,91)), 'Incomplete alphabet'
    glyphs=bytes(int(row,2) for c in range(32,91) for row in GLYPHS.get(chr(c), ('00000',)*7))
    def array(name, values):
        return 'static const unsigned char '+name+'['+str(len(values))+']={\n'+',\n'.join(
            ','.join(str(v) for v in values[i:i+32]) for i in range(0,len(values),32))+'\n};\n'
    def pen(rgb):
        return min(range(64),key=lambda p:sum((palette[3*p+c]-rgb[c])**2 for c in range(3)))
    header='/* Generated by tools/generate_ready_audio_ui.py; exact accepted palette. */\n'
    header+=array('readyUiBackgroundRle',packed)+array('readyUiBaseMask',mask)+array('readyUiGlyphs',glyphs)
    header+=f'#define READY_UI_CYAN {pen((31,201,224))}\n#define READY_UI_CREAM {pen((241,221,170))}\n#define READY_UI_GREY {pen((180,190,183))}\n'
    (ROOT/'src/ready_ui_data.h').write_text(header)
    print('READY UI immutable bytes:',len(packed)+len(mask)+len(glyphs),'(background RLE',len(packed),')')

if __name__ == '__main__': generate()
