"""Offline READY band rasterization and transition bounds; never runs on Amiga.

Layout lives in ready_ui_layout.c. Five disjoint bands retain current-state dust
margins. Deduplicate band variants, not complete menu combinations.
"""
from pathlib import Path
import ctypes as c
import subprocess, tempfile, json, sys
ROOT=Path(__file__).resolve().parents[1]
U8=c.c_ubyte; PTR=c.POINTER(U8)
class Layout(c.Structure):
    _fields_=[('background',U8*17472),('patch',U8*17472),('previous',(U8*17472)*2),('mask',U8*2912)]
class Selection(c.Structure):
    _fields_=[(n,U8) for n in ('page','row','secondary','section','mode','sfx','track','status')]
BANDS=[(0,26),(26,16),(42,16),(58,20),(78,26)]
def selections():
    yield from [(Selection(0,r,0,0,0,0,0,0),1) for r in range(2)]
    for hd in (1,0):
        for second in range(2):
            for section in range(2):
                for mode in range(3):
                    for row in range(5 if hd else 4):
                        yield Selection(1,row,second,section,mode,0,0,0),hd
    for sfx in range(16):
        for track in range(5):
            for status in range(4):
                for row in range(3):
                    yield Selection(2,row,0,0,0,sfx,track,status),1

def rasterize(source,include):
    with tempfile.TemporaryDirectory() as td:
        lib=Path(td)/'layout.so'
        subprocess.run(['cc','-shared','-fPIC','-O2','-I'+str(include),str(source),'-o',str(lib)],check=True)
        dll=c.CDLL(str(lib));ui=Layout()
        raw=(ROOT/'assets/runtime/readymenu.spbm').read_bytes()[204:]
        planes=[(U8*29952).from_buffer_copy(raw[p*29952:(p+1)*29952]) for p in range(6)]
        atlas=(PTR*6)(*[c.cast(p,PTR) for p in planes])
        dll.readyUiInit(c.byref(ui),atlas)
        for s,hd in selections():
            dll.readyUiCompose(c.byref(ui),atlas,c.byref(s),hd)
            # Main-page mask is supplied by legacy ready_dust, not this cache.
            yield s,hd,bytes(ui.patch),bytes(ui.mask) if s.page else bytes(2912)

def array(name,ctype,values,columns=24):
    return 'static const '+ctype+' '+name+'[]={\n'+',\n'.join(','.join(map(str,values[i:i+columns])) for i in range(0,len(values),columns))+'\n};\n'

def generate(adf=False):
    variants=[[] for _ in BANDS]; mapping=[]
    for s,hd,pixels,mask in rasterize(ROOT/'tools/ready_ui_layout.c',ROOT/'src'):
        if adf and s.page and hd: continue
        for b,(y,h) in enumerate(BANDS):
            data=b''.join(pixels[p*2912+y*28:p*2912+(y+h)*28] for p in range(6))+mask[y*28:(y+h)*28]
            if data not in variants[b]: variants[b].append(data)
            mapping.append(variants[b].index(data))
    pool=bytearray(); offsets=[]; bounds=[]; bases=[]; counts=[]; transition_bases=[]
    for b,((y,h),vv) in enumerate(zip(BANDS,variants)):
        bases.append(len(offsets));counts.append(len(vv));transition_bases.append(len(bounds))
        previous=bytes(len(vv[0]))
        for v in vv:
            offsets.append(len(pool));pool.extend(a^b for a,b in zip(v,previous))
            previous=v
        for a in vv:
            for z in vv:
                positions=[(yy,x) for yy in range(h) for x in range(28)
                           if any(a[p*h*28+yy*28+x]!=z[p*h*28+yy*28+x] for p in range(6))]
                if positions:
                    bounds.extend([min(yy for yy,x in positions),max(yy for yy,x in positions)+1,
                                   min(x for yy,x in positions)&~1,(max(x for yy,x in positions)+2)&~1])
                else: bounds.extend([0,0,0,0])
    # Delta stream: 0..127 = 1..128 zero bytes; 128..255 = literal bytes.
    # Literal runs avoid doubling high-entropy glyph deltas as count/value RLE.
    packed=[];i=0
    while i<len(pool):
        end=i
        if pool[i]==0:
            while end<min(i+128,len(pool)) and pool[end]==0:end+=1
            packed.append(end-i-1)
        else:
            while end<min(i+128,len(pool)) and pool[end]!=0:end+=1
            packed.append(128+end-i-1);packed.extend(pool[i:end])
        i=end
    header='/* Generated by tools/generate_ready_ui_cache.py. Do not edit. */\n'
    for name,ctype,values in [('readyUiRle','unsigned char',packed),('readyUiOffsets','unsigned long',offsets),
            ('readyUiBounds','unsigned char',bounds),('readyUiMap','unsigned char',mapping),
            ('readyUiBases','unsigned short',bases),('readyUiCounts','unsigned char',counts),
            ('readyUiTransitions','unsigned long',transition_bases),('readyUiY','unsigned char',[y for y,h in BANDS]),
            ('readyUiHeight','unsigned char',[h for y,h in BANDS])]: header+=array(name,ctype,values)
    suffix='_adf' if adf else ''
    outputs={'ready_ui_cache'+suffix+'_data.h':header,'ready_ui_cache'+suffix+'_size.h':
             '/* Generated cache allocation, CPU-only Fast RAM. */\n#define READY_UI_CACHE_BYTES '+str(len(pool))+'\n'}
    for name,content in outputs.items():
        path=ROOT/'src'/name
        if '--check' in sys.argv:assert path.read_text()==content,'Stale generated cache: '+name
        else:path.write_text(content)
    print(json.dumps(dict(variants=counts,cache_bytes=len(pool),rle_bytes=len(packed),bounds_bytes=len(bounds),mapping_bytes=len(mapping))))
if __name__=='__main__':
    generate()
    generate(adf=True)
